export const languages = [
    { value: "Afrikaans", id: "af_ZA" },
    { value: "Shqip", id: "sq_AL" },
    { value: "العربية", id: "ar_AR" },
    { value: "Հայերեն", id: "hy_AM" },
    { value: "Azərbaycan dili", id: "az_AZ" },
    { value: "Euskara", id: "eu_ES" },
    { value: "Беларуская", id: "be_BY" },
    { value: "বাংলা", id: "bn_IN" },
    { value: "Bosanski", id: "bs_BA" },
    { value: "Български", id: "bg_BG" },
    { value: "Català", id: "ca_ES" },
    { value: "Bisaya", id: "cx_PH" },
    { value: "Hrvatski", id: "hr_HR" },
    { value: "Čeština", id: "cs_CZ" },
    { value: "Dansk", id: "da_DK" },
    { value: "Nederlands", id: "nl_NL" },
    { value: "Nederlands (België)", id: "nl_BE" },
    { value: "English (UK)", id: "en_GB" },
    { value: "English (US)", id: "en_US" },
    { value: "Eesti", id: "et_EE" },
    { value: "Filipino", id: "tl_PH" },
    { value: "Suomi", id: "fi_FI" },
    { value: "Français (Canada)", id: "fr_CA" },
    { value: "Français (France)", id: "fr_FR" },
    { value: "Frysk", id: "fy_NL" },
    { value: "Galego", id: "gl_ES" },
    { value: "ქართული", id: "ka_GE" },
    { value: "Deutsch", id: "de_DE" },
    { value: "Ελληνικά", id: "el_GR" },
    { value: "Guarani", id: "gn_PY" },
    { value: "ગુજરાતી", id: "gu_IN" },
    { value: "עברית", id: "he_IL" },
    { value: "हिन्दी", id: "hi_IN" },
    { value: "Magyar", id: "hu_HU" },
    { value: "Íslenska", id: "is_IS" },
    { value: "Bahasa Indonesia", id: "id_ID" },
    { value: "Italiano", id: "it_IT" },
    { value: "日本語", id: "ja_JP" },
    { value: "日本語(関西)", id: "ja_KS" },
    { value: "Basa Jawa", id: "jv_ID" },
    { value: "ಕನ್ನಡ", id: "kn_IN" },
    { value: "Қазақша", id: "kk_KZ" },
    { value: "한국어", id: "ko_KR" },
    { value: "Kurdî (Kurmancî)", id: "ku_TR" },
    { value: "Latviešu", id: "lv_LV" },
    { value: "Lietuvių", id: "lt_LT" },
    { value: "Македонски", id: "mk_MK" },
    { value: "Bahasa Melayu", id: "ms_MY" },
    { value: "മലയാളം", id: "ml_IN" },
    { value: "मराठी", id: "mr_IN" },
    { value: "Монгол", id: "mn_MN" },
    { value: "नेपाली", id: "ne_NP" },
    { value: "Norsk (bokmål)", id: "nb_NO" },
    { value: "Norsk (nynorsk)", id: "nn_NO" },
    { value: "پښتو", id: "ps_AF" },
    { value: "فارسی", id: "fa_IR" },
    { value: "Polski", id: "pl_PL" },
    { value: "Português (Brasil)", id: "pt_BR" },
    { value: "Português (Portugal)", id: "pt_PT" },
    { value: "ਪੰਜਾਬੀ", id: "pa_IN" },
    { value: "Română", id: "ro_RO" },
    { value: "Русский", id: "ru_RU" },
    { value: "Српски", id: "sr_RS" },
    { value: "中文(简体)", id: "zh_CN" },
    { value: "සිංහල", id: "si_LK" },
    { value: "Slovenčina", id: "sk_SK" },
    { value: "Slovenščina", id: "sl_SI" },
    { value: "Español", id: "es_LA" },
    { value: "Español (Colombia)", id: "es_CO" },
    { value: "Español (España)", id: "es_ES" },
    { value: "Kiswahili", id: "sw_KE" },
    { value: "Svenska", id: "sv_SE" },
    { value: "Тоҷикӣ", id: "tg_TJ" },
    { value: "தமிழ்", id: "ta_IN" },
    { value: "తెలుగు", id: "te_IN" },
    { value: "ภาษาไทย", id: "th_TH" },
    { value: "中文(香港)", id: "zh_HK" },
    { value: "中文(台灣)", id: "zh_TW" },
    { value: "Türkçe", id: "tr_TR" },
    { value: "Українська", id: "uk_UA" },
    { value: "اردو", id: "ur_PK" },
    { value: "O'zbek", id: "uz_UZ" },
    { value: "Tiếng Việt", id: "vi_VN" },
    { value: "Cymraeg", id: "cy_GB" },
]
