export const languages = [
    { name: "English", id: "en" },
    // { name: "English (UK)", id: "en_GB" },
    // { name: "English (US)", id: "en_US" },
    { name: "日本語", id: "ja" },
    // { name: "日本語", id: "ja_JP" },
    // { name: "日本語(関西)", id: "ja_KS" },
    { name: "中文", id: "zh" },
    // { name: "中文(香港)", id: "zh_HK" },
    // { name: "中文(台灣)", id: "zh_TW" },
    { name: "한국어", id: "ko" },
    { name: "Afrikaans", id: "af" },
    { name: "Shqip", id: "sq" },
    { name: "العربية", id: "ar" },
    { name: "Հայերեն", id: "hy" },
    { name: "Azərbaycan dili", id: "az" },
    { name: "Euskara", id: "eu" },
    { name: "Беларуская", id: "be" },
    { name: "বাংলা", id: "bn" },
    { name: "Bosanski", id: "bs" },
    { name: "Български", id: "bg" },
    { name: "Català", id: "ca" },
    { name: "Bisaya", id: "ceb" },
    { name: "Hrvatski", id: "hr" },
    { name: "Čeština", id: "cs" },
    { name: "Dansk", id: "da" },
    { name: "Nederlands", id: "nl" },
    // { name: "Nederlands (België)", id: "nl-BE" },
    { name: "Eesti", id: "et" },
    { name: "Filipino", id: "fil" },
    { name: "Suomi", id: "fi" },
    // { name: "Français (Canada)", id: "fr-CA" },
    // { name: "Français (France)", id: "fr" },
    { name: "Français (France)", id: "fr" },
    { name: "Frysk", id: "fy" },
    { name: "Galego", id: "gl" },
    { name: "ქართული", id: "ka" },
    { name: "Deutsch", id: "de" },
    { name: "Ελληνικά", id: "el" },
    { name: "Guarani", id: "gn" },
    { name: "ગુજરાતી", id: "gu" },
    { name: "עברית", id: "he" },
    { name: "हिन्दी", id: "hi" },
    { name: "Magyar", id: "hu" },
    { name: "Íslenska", id: "is" },
    { name: "Bahasa Indonesia", id: "id" },
    { name: "Italiano", id: "it" },
    { name: "Basa Jawa", id: "jv" },
    { name: "ಕನ್ನಡ", id: "kn" },
    { name: "Қазақша", id: "kk" },
    { name: "Kurdî (Kurmancî)", id: "ku" },
    { name: "Latviešu", id: "lv" },
    { name: "Lietuvių", id: "lt" },
    { name: "Македонски", id: "mk" },
    { name: "Bahasa Melayu", id: "ms" },
    { name: "മലയാളം", id: "ml" },
    { name: "मराठी", id: "mr" },
    { name: "Монгол", id: "mn" },
    { name: "नेपाली", id: "ne" },
    { name: "Norsk (bokmål)", id: "nb" },
    { name: "Norsk (nynorsk)", id: "nn" },
    { name: "پښتو", id: "ps" },
    { name: "فارسی", id: "fa" },
    { name: "Polski", id: "pl" },
    // { name: "Português (Brasil)", id: "pt-BR" },
    // { name: "Português (Portugal)", id: "pt" },
    { name: "Português", id: "pt" },
    { name: "ਪੰਜਾਬੀ", id: "pa" },
    { name: "Română", id: "ro" },
    { name: "Русский", id: "ru" },
    { name: "Српски", id: "sr" },
    //{ name: "中文(简体)", id: "zh-CN" },
    { name: "සිංහල", id: "si" },
    { name: "Slovenčina", id: "sk" },
    { name: "Slovenščina", id: "sl" },
    { name: "Español", id: "es" },
    // { name: "Español (Colombia)", id: "es-CO" },
    // { name: "Español (España)", id: "es-ES" },
    { name: "Kiswahili", id: "sw" },
    { name: "Svenska", id: "sv" },
    { name: "Тоҷикӣ", id: "tg" },
    { name: "தமிழ்", id: "ta" },
    { name: "తెలుగు", id: "te" },
    { name: "ภาษาไทย", id: "th" },
    { name: "Türkçe", id: "tr" },
    { name: "Українська", id: "uk" },
    { name: "اردو", id: "ur" },
    { name: "O'zbek", id: "uz" },
    { name: "Tiếng Việt", id: "vi" },
    { name: "Cymraeg", id: "cy" },
]
