"use client"

import { Metadata } from "next"
import React, { Suspense } from "react"
import { RecoilRoot } from "recoil"

export const metadata: Metadata = {
    title: "Realtime-Interpretation-Service",
    description: "Generated by create next app",
}

export default function Provider({ children }: { children: React.ReactNode }) {
    return (
        <Suspense>
            <RecoilRoot>{children}</RecoilRoot>
        </Suspense>
    )
}
