"use client"

import { Metadata } from "next"
import { SessionProvider } from "next-auth/react"
import React, { Suspense } from "react"
import { RecoilRoot } from "recoil"

export const metadata: Metadata = {
    title: "Realtime-Interpretation-Service",
    description: "Generated by create next app",
}

export default function Provider({ children }: { children: React.ReactNode }) {
    return (
        <Suspense>
            <SessionProvider>
                <RecoilRoot>{children}</RecoilRoot>
            </SessionProvider>
        </Suspense>
    )
}
